apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-app
  namespace: demo
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: devmembershipregistry.azurecr.io/helloworld-2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health/ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /health/ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
      restartPolicy: Always