apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld
spec:
  replicas: 3
  selector:
    app: helloworld
  template:
    metadata:
      name: helloworld
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: devmembershipregistry.azurecr.io/helloworld:latest
        ports:
        - containerPort: 8080